#.travis.yml

sudo: required
dist: trusty

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - /^dep-update-.*$/

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then webpack --env.aot --env.client; webpack --env.aot --env.server; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then webpack --env.aot --env.client; webpack --env.aot --env.server; fi'